apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-cricket-score-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-cricket-score
  template:
    metadata:
      labels:
        app: live-cricket-score
    spec:
      containers:
        - name: live-cricket-score-container
          image: gcr.io/rugged-feat-465115-p7/live-cricket-score-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: live-cricket-score-service
spec:
  selector:
    app: live-cricket-score
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
