steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/x-landing-466108-p9/live-cricket-score-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/x-landing-466108-p9/live-cricket-score-app:$SHORT_SHA']

  -  name: "gcr.io/cloud-builders/gke-deploy"
     args:
     - run
     - --filename=app.yaml
     - --location=us-central1
     - --cluster=autopilot-cluster-1
images:
  - 'gcr.io/x-landing-466108-p9/live-cricket-score-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

